[1m[31mERROR   [0m root:management_page.py:68 Error occurred during deletion: Locator.click: Timeout 30000ms exceeded.
Call log:
waiting for locator("[data-testid='DeleteOutlineOutlinedIcon']").first